### ISSUE TITLE
Rethinking question flagging and lower thirds

### ISSUE THREAD

**Issue by imikerussell** [Hennamann/Live-Chat-Question-Flagger#10]
Today I was running and using the app mostly by myself (Joe was also helping plenty) and it got me to thinking about making an easier workflow for both hosts and producers.

Some hosts will not have the luxury of a producer so perhaps it's worth to have "Mark as Question" and "Generate lower third" as icons/options on the **same page** and in the **same** chat stream.

e.g. Instead of "Mark as Question" sending the chat to another page it would simply highlight the chat message with a light orange background.

![question-highlight](https://user-images.githubusercontent.com/5058188/29628248-d93bf66a-882c-11e7-85d0-b33882627db1.jpg)

That way any chat message can go straight "on air" and if the host does have a producer around they can highlight chats making it easy for the host to scroll through and generate a lower third.

**Comment by Hennamann** [comment]
This is a great idea!

Once i have ironed out some of the bugs that still remain, i will start work on this!

**Comment by Hennamann** [comment]
This has been added in commit 2b4a87d functionality is pretty much what is described in this issue. Documentation will be changed to reflect this very soon.
