### ISSUE TITLE
Connect with Facebook Live Chat API

### ISSUE THREAD

**Issue by imikerussell** [Hennamann/Live-Chat-Question-Flagger#3]
Ability to pull in comments from a Facebook Live video is documented here: https://developers.facebook.com/docs/graph-api/reference/live-video/comments/

**Comment by Hennamann** [comment]
For the facebook live api, we should be able to use this npm module: https://www.npmjs.com/package/facebook-chat-api

**Comment by Hennamann** [comment]
This has now been done in commit:  6fbd797 
A custom Node Module was made for this here: https://github.com/Hennamann/facebook-live-chat
